[package]
name = "bm-core"
version.workspace = true
edition.workspace = true
repository.workspace = true

[dependencies]
bm-contract = { workspace = true }
# F-12:依赖倒置后 bm-core 彻底去 persist/rusqlite 化
tokio = { workspace = true }
tokio-util = { workspace = true }
async-trait = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
chrono = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }

[lints]
workspace = true
