[package]
name = "boenmind-shell"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/SadBoen/BoenMind"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(cfg_tauri)'] }
