[package]
name = "bm-runtime"
version.workspace = true
edition.workspace = true
repository.workspace = true

[dependencies]
bm-contract = { workspace = true }
bm-core = { workspace = true }
bm-providers = { workspace = true }
bm-surface-http = { workspace = true }
bm-persist = { workspace = true }
axum = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
dirs = { workspace = true }

[lints]
workspace = true
