[package]
name = "bm-providers"
version.workspace = true
edition.workspace = true
repository.workspace = true

[dependencies]
bm-contract = { workspace = true }
bm-core = { workspace = true }
async-trait = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
keyring = { workspace = true }
reqwest = { version = "0.12", optional = true, default-features = false, features = ["json", "rustls-tls"] }
tokio = { workspace = true }
tracing = { workspace = true }
aes-gcm = "0.11.1"
tokio-util.workspace = true
serde.workspace = true
getrandom = "0.4.3"

[features]
glm = ["dep:reqwest"]

[dev-dependencies]
tokio = { workspace = true }

[lints]
workspace = true
