[package]
name = "bm-providers"
version.workspace = true
edition.workspace = true
repository.workspace = true

[dependencies]
bm-contract = { workspace = true }
bm-core = { workspace = true }
bm-persist = { workspace = true }
async-trait = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
keyring = { workspace = true }
reqwest = { workspace = true, features = ["stream"] }
tokio = { workspace = true }
tracing = { workspace = true }
aes-gcm = { workspace = true }
tokio-util.workspace = true
serde.workspace = true
getrandom = { workspace = true }
sha2 = { workspace = true }
grep-searcher = { workspace = true }
grep-regex = { workspace = true }
walkdir = { workspace = true }
regex = { workspace = true }

[features]
glm = []

[dev-dependencies]
tokio = { workspace = true }
tempfile = "3"

[lints]
workspace = true
